//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCecep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccarea
    {
        public ccarea()
        {
            this.ccpeticion = new HashSet<ccpeticion>();
            this.ccempresa = new HashSet<ccempresa>();
        }
    
        public int ccareaid { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<ccpeticion> ccpeticion { get; set; }
        public virtual ICollection<ccempresa> ccempresa { get; set; }
    }
}
