//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCecep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccnoticia
    {
        public int ccnoticiaid { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechapublic { get; set; }
        public Nullable<System.DateTime> fechavenc { get; set; }
    }
}
