//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCecep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccpeticiondet
    {
        public ccpeticiondet()
        {
            this.ccpeticionserv = new HashSet<ccpeticionserv>();
        }
    
        public int ccpeticiondetid { get; set; }
        public int ccpeticionid { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cctiposervid { get; set; }
    
        public virtual ccpeticion ccpeticion { get; set; }
        public virtual cctiposerv cctiposerv { get; set; }
        public virtual ICollection<ccpeticionserv> ccpeticionserv { get; set; }
    }
}
