//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCecep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccpeticionserv
    {
        public int ccpeticionservid { get; set; }
        public int ccpeticiondetid { get; set; }
        public int cctiposerviciodetid { get; set; }
        public bool estado { get; set; }
    
        public virtual ccpeticiondet ccpeticiondet { get; set; }
        public virtual cctiposervdet cctiposervdet { get; set; }
    }
}
