//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCecep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CecepEntities : DbContext
    {
        public CecepEntities()
            : base("name=CecepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ccarea> ccarea { get; set; }
        public DbSet<cccurso> cccurso { get; set; }
        public DbSet<ccempresa> ccempresa { get; set; }
        public DbSet<ccevento> ccevento { get; set; }
        public DbSet<ccnoticia> ccnoticia { get; set; }
        public DbSet<ccpeticion> ccpeticion { get; set; }
        public DbSet<ccpeticiondet> ccpeticiondet { get; set; }
        public DbSet<cctiposerv> cctiposerv { get; set; }
        public DbSet<cctiposervdet> cctiposervdet { get; set; }
        public DbSet<ccpeticionserv> ccpeticionserv { get; set; }
        public DbSet<cctiposervcat> cctiposervcat { get; set; }
    }
}
